# Generated by Django 3.1.1 on 2020-09-25 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stackmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 25, 6, 0, 26, 140756, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
